In [1]:
import sys
import os
# Adds the project root directory to the Python path.
# The notebook is in 'Examples/Symmetry Reduction', so we need to go up two levels.
project_root = os.path.abspath('../..')
if project_root not in sys.path:
    sys.path.insert(0, project_root)

In [6]:
from pysymmetry import FiniteGroup, representation
from sage.all import matrix, QQ

# 1. Define the D4 group using its generators (a rotation and a reflection)
# The group acts on 4 vertices labeled {1, 2, 3, 4}
rotation = "(1,2,3,4)" ; reflection = "(1,3)"
G = FiniteGroup([rotation, reflection], matrix=False)

# 2. Define the natural permutation representation
phi = G.natural_representation()

# 3. Define a G-equivariant matrix M
# 'a' for diagonal, 'b' for adjacent, 'c' for opposite vertices
a, b, c = 10, 2, 1
M = matrix(QQ, [[a, b, c, b],
                [b, a, b, c],
                [c, b, a, b],
                [b, c, b, a]])

# 4. Compute the symmetry-adapted basis via the main function
P = G.a base_equivariant_to_blocks(phi)


# 5. Perform the block-diagonalization
M_block_diagonal = P.inverse() * M * P

# Display results
print("Original Matrix M:\n", M)
print("\nBlock-Diagonal Matrix P^{-1}MP:\n", M_block_diagonal)

Original Matrix M:
 [10  2  1  2]
[ 2 10  2  1]
[ 1  2 10  2]
[ 2  1  2 10]

Block-Diagonal Matrix P^{-1}MP:
 [15  0  0  0]
[ 0  7  0  0]
[ 0  0  9  0]
[ 0  0  0  9]


In [1]:
import numpy as np
import scipy as sp
print(f"NumPy version: {np.__version__}")
print(f"SciPy version: {sp.__version__}")

NumPy version: 1.26.4
SciPy version: 1.14.1


In [5]:
version()

'SageMath version 10.4, Release Date: 2024-07-19'

In [7]:
python3.__version__

NameError: name 'python3' is not defined

In [8]:
import sys
print(sys.version)

3.11.10 | packaged by conda-forge | (main, Sep 22 2024, 14:10:38) [GCC 13.3.0]
